package com.hmdp.ai.domain.workflow;

public enum WorkflowNodeType {
    START, INPUT_VALIDATION, INPUT_NORMALIZE, INTENT_CLASSIFY, ENTITY_EXTRACT, QUERY_REWRITE,
    KNOWLEDGE_RETRIEVE, SEMANTIC_SEARCH, EXTERNAL_SEARCH, LLM, TOOL, MCP_TOOL, DIFY_WORKFLOW,
    DOCUMENT_PARSE, TEXT_TRANSFORM, LONG_TEXT_MAP_REDUCE, DATA_TRANSFORM, MEMORY_RECALL, BRANCH, PARALLEL, JOIN,
    FOREACH, LOOP, HUMAN_FEEDBACK, HUMAN_APPROVAL, CITATION_VALIDATION, OUTPUT_VALIDATION,
    ARTIFACT_GENERATE, END
}
