package com.hmdp.ai.application.mcp;
import com.fasterxml.jackson.databind.ObjectMapper;import com.hmdp.ai.application.dto.mcp.*;import com.hmdp.ai.application.security.AiAccessGuard;import com.hmdp.ai.domain.mcp.*;import com.hmdp.ai.domain.security.*;import com.hmdp.ai.shared.id.AiIdGenerator;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.net.URI;import java.util.*;import java.util.stream.Collectors;
@Service public class McpApplicationService {private final McpRepository repository;private final AiAccessGuard access;private final AiIdGenerator ids;private final ObjectMapper mapper;private final McpManagementPort management;public McpApplicationService(McpRepository repository,AiAccessGuard access,AiIdGenerator ids,ObjectMapper mapper,McpManagementPort management){this.repository=repository;this.access=access;this.ids=ids;this.mapper=mapper;this.management=management;}
    @Transactional public McpServerResponse create(CreateMcpServerRequest r){AiSecurityContext c=access.require(AiPermission.MCP_MANAGE);if(!c.getAuthorization().has(AiPermission.ADMIN))throw new IllegalArgumentException("ADMIN_REQUIRED");validate(r);String allowed;try{allowed=mapper.writeValueAsString(r.getAllowedTools());}catch(Exception e){throw new IllegalArgumentException("allowedTools is invalid",e);}McpServer server=new McpServer(ids.nextId(),c.getTenant().getTenantId(),c.getWorkspace().getWorkspaceId(),r.getCode(),r.getName(),r.getNamespace(),r.getTransport(),r.getEndpoint(),blank(r.getSecretRef()),allowed,r.getTimeoutMs(),r.isAllowPrivateNetwork(),"UNKNOWN",r.isEnabled(),null,"ACTIVE");return new McpServerResponse(repository.create(server,c.getUserId()));}
    public List<McpServerResponse>list(){AiSecurityContext c=access.require(AiPermission.MCP_MANAGE);return repository.findAll(c.getTenant().getTenantId(),c.getWorkspace().getWorkspaceId()).stream().map(McpServerResponse::new).collect(Collectors.toList());}
    public McpHealthResponse health(String id){AiSecurityContext c=access.require(AiPermission.MCP_MANAGE);McpServer s=require(c,id);String status=management.checkHealth(s);repository.updateHealth(s.getTenantId(),s.getWorkspaceId(),s.getId(),status,c.getUserId());return new McpHealthResponse(id,status);}
    @Transactional public McpSyncResponse sync(String id){AiSecurityContext c=access.require(AiPermission.MCP_MANAGE);McpServer s=require(c,id);return new McpSyncResponse(id,management.syncTools(s,c.getUserId()));}
    private McpServer require(AiSecurityContext c,String id){return repository.find(c.getTenant().getTenantId(),c.getWorkspace().getWorkspaceId(),id).orElseThrow(()->new IllegalArgumentException("MCP_SERVER_NOT_FOUND"));}
    private void validate(CreateMcpServerRequest r){URI uri;try{uri=URI.create(r.getEndpoint());}catch(Exception e){throw new IllegalArgumentException("MCP_ENDPOINT_INVALID",e);}if(uri.getHost()==null||!("http".equalsIgnoreCase(uri.getScheme())||"https".equalsIgnoreCase(uri.getScheme())))throw new IllegalArgumentException("MCP_ENDPOINT_INVALID");if(r.getSecretRef()!=null&&!r.getSecretRef().isEmpty()&&!r.getSecretRef().matches("env:[A-Z][A-Z0-9_]{1,127}"))throw new IllegalArgumentException("MCP_SECRET_REFERENCE_INVALID");}private String blank(String v){return v==null||v.trim().isEmpty()?null:v;}}
