package com.hmdp.ai.domain.tool;

import com.hmdp.ai.domain.security.AiPermission;
import java.util.ArrayList;import java.util.Collections;import java.util.List;

public final class ToolVersionDraft {
    private final String id,tenantId,workspaceId,toolId,name,description,inputSchema,outputSchema,retryPolicyJson,configurationJson,contentHash,changeNote;
    private final int version,timeoutMs; private final ToolProtocol protocol; private final ToolRiskLevel riskLevel;
    private final boolean sideEffect,idempotent,enabled; private final List<AiPermission> requiredPermissions;
    public ToolVersionDraft(String id,String tenantId,String workspaceId,String toolId,int version,String name,String description,ToolProtocol protocol,String inputSchema,String outputSchema,ToolRiskLevel riskLevel,boolean sideEffect,boolean idempotent,int timeoutMs,String retryPolicyJson,List<AiPermission> requiredPermissions,String configurationJson,boolean enabled,String contentHash,String changeNote){this.id=id;this.tenantId=tenantId;this.workspaceId=workspaceId;this.toolId=toolId;this.version=version;this.name=name;this.description=description;this.protocol=protocol;this.inputSchema=inputSchema;this.outputSchema=outputSchema;this.riskLevel=riskLevel;this.sideEffect=sideEffect;this.idempotent=idempotent;this.timeoutMs=timeoutMs;this.retryPolicyJson=retryPolicyJson;this.requiredPermissions=Collections.unmodifiableList(new ArrayList<>(requiredPermissions));this.configurationJson=configurationJson;this.enabled=enabled;this.contentHash=contentHash;this.changeNote=changeNote;}
    public String getId(){return id;}public String getTenantId(){return tenantId;}public String getWorkspaceId(){return workspaceId;}public String getToolId(){return toolId;}public int getVersion(){return version;}public String getName(){return name;}public String getDescription(){return description;}public ToolProtocol getProtocol(){return protocol;}public String getInputSchema(){return inputSchema;}public String getOutputSchema(){return outputSchema;}public ToolRiskLevel getRiskLevel(){return riskLevel;}public boolean isSideEffect(){return sideEffect;}public boolean isIdempotent(){return idempotent;}public int getTimeoutMs(){return timeoutMs;}public String getRetryPolicyJson(){return retryPolicyJson;}public List<AiPermission> getRequiredPermissions(){return requiredPermissions;}public String getConfigurationJson(){return configurationJson;}public boolean isEnabled(){return enabled;}public String getContentHash(){return contentHash;}public String getChangeNote(){return changeNote;}
}
