package com.hmdp.ai.domain.feedback;

public enum FeedbackTag {
    FACT_ERROR, MISSING_INFORMATION, WRONG_CITATION, OUTDATED_KNOWLEDGE, WRONG_TOOL, WRONG_INTENT,
    FORMAT_ERROR, TOO_VERBOSE, TOO_BRIEF, UNSAFE, OTHER
}
