package com.hmdp.ai.domain.security;

public enum AiPermission {
    AGENT_RUN, AGENT_MANAGE, PROMPT_MANAGE, MODEL_MANAGE, WORKFLOW_MANAGE,
    TOOL_MANAGE, MCP_MANAGE, KNOWLEDGE_READ, KNOWLEDGE_WRITE, KNOWLEDGE_PUBLISH,
    MEMORY_READ, MEMORY_DELETE, MEMORY_MANAGE, FEEDBACK_SUBMIT, EVALUATION_RUN, EVALUATION_MANAGE,
    TOOL_APPROVE, RUN_INSPECT, ARTIFACT_READ, ADMIN
}
