package com.hmdp.ai.application.tool;

import com.fasterxml.jackson.databind.JsonNode;import com.fasterxml.jackson.databind.ObjectMapper;
import com.hmdp.ai.application.dto.PageResponse;import com.hmdp.ai.application.dto.tool.CreateToolRequest;import com.hmdp.ai.application.dto.tool.ToolResponse;import com.hmdp.ai.application.security.AiAccessGuard;import com.hmdp.ai.domain.security.AiPermission;import com.hmdp.ai.domain.security.AiSecurityContext;import com.hmdp.ai.domain.tool.*;import com.hmdp.ai.shared.id.AiIdGenerator;import com.hmdp.ai.shared.json.ContentHashService;import com.hmdp.ai.shared.validation.JsonSchemaValidationService;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.util.*;import java.util.stream.Collectors;

@Service public class ToolApplicationService {private final ToolCatalogRepository repository;private final AiAccessGuard access;private final AiIdGenerator ids;private final ContentHashService hashes;private final JsonSchemaValidationService schemas;private final ObjectMapper mapper;public ToolApplicationService(ToolCatalogRepository repository,AiAccessGuard access,AiIdGenerator ids,ContentHashService hashes,JsonSchemaValidationService schemas,ObjectMapper mapper){this.repository=repository;this.access=access;this.ids=ids;this.hashes=hashes;this.schemas=schemas;this.mapper=mapper;}
    @Transactional public ToolResponse create(CreateToolRequest request){AiSecurityContext c=access.require(AiPermission.TOOL_MANAGE);requireSchema(request.getInputSchema(),"inputSchema");requireSchema(request.getOutputSchema(),"outputSchema");validateJson(request.getRetryPolicyJson(),"retryPolicyJson");JsonNode configuration=validateJson(request.getConfigurationJson(),"configurationJson");rejectPlainSecrets(configuration);String toolId=ids.nextId();ToolCatalogEntry tool=new ToolCatalogEntry(toolId,c.getTenant().getTenantId(),c.getWorkspace().getWorkspaceId(),request.getCode(),request.getName(),request.getDescription(),1,"ACTIVE");Map<String,Object> content=new LinkedHashMap<>();content.put("protocol",request.getProtocol());content.put("inputSchema",request.getInputSchema());content.put("outputSchema",request.getOutputSchema());content.put("riskLevel",request.getRiskLevel());content.put("sideEffect",request.isSideEffect());content.put("idempotent",request.isIdempotent());content.put("timeoutMs",request.getTimeoutMs());content.put("retryPolicy",request.getRetryPolicyJson());content.put("permissions",request.getRequiredPermissions());content.put("configuration",request.getConfigurationJson());ToolVersionDraft version=new ToolVersionDraft(ids.nextId(),tool.getTenantId(),tool.getWorkspaceId(),toolId,1,request.getName(),request.getDescription(),request.getProtocol(),request.getInputSchema(),request.getOutputSchema(),request.getRiskLevel(),request.isSideEffect(),request.isIdempotent(),request.getTimeoutMs(),request.getRetryPolicyJson(),request.getRequiredPermissions(),request.getConfigurationJson(),request.isEnabled(),hashes.sha256(content),request.getChangeNote());return new ToolResponse(repository.create(tool,version,c.getUserId()));}
    public PageResponse<ToolResponse> list(int page,int size){AiSecurityContext c=access.require(AiPermission.TOOL_MANAGE);int offset=Math.multiplyExact(page-1,size);List<ToolResponse> items=repository.findPage(c.getTenant().getTenantId(),c.getWorkspace().getWorkspaceId(),offset,size).stream().map(ToolResponse::new).collect(Collectors.toList());return new PageResponse<>(items,repository.count(c.getTenant().getTenantId(),c.getWorkspace().getWorkspaceId()),page,size);}
    private JsonNode validateJson(String json,String field){try{return mapper.readTree(json);}catch(Exception e){throw new IllegalArgumentException(field+" is invalid JSON",e);}}
    private void requireSchema(String schema,String field){if(!schemas.validateSchema(schema,field).isValid())throw new IllegalArgumentException(field+" is invalid JSON Schema");}
    private void rejectPlainSecrets(JsonNode node){if(node.isObject()){node.fields().forEachRemaining(entry->{String key=entry.getKey().toLowerCase(Locale.ROOT);JsonNode value=entry.getValue();if((key.contains("password")||key.contains("api_key")||key.contains("apikey")||key.equals("secret")||key.equals("token"))&&value.isTextual()&&!value.asText().startsWith("env:"))throw new IllegalArgumentException("tool configuration contains a plaintext secret: "+entry.getKey());rejectPlainSecrets(value);});}else if(node.isArray())node.forEach(this::rejectPlainSecrets);}
}
