-- Replace the compatibility-shaped default graph with native runtime nodes.
DELETE FROM ai_workflow_edge WHERE workflow_version_id='workflow-shop-consultant-v1';
DELETE FROM ai_workflow_node WHERE workflow_version_id='workflow-shop-consultant-v1';

INSERT INTO ai_workflow_node
(id,tenant_id,workspace_id,workflow_version_id,node_code,node_type,name,configuration_json,input_mapping_json,output_mapping_json,timeout_ms,max_attempts,status,created_by,updated_by)
VALUES
('wf-shop-v1-start','default','default','workflow-shop-consultant-v1','start','START','Start','{}','{}','{}',1000,1,'ACTIVE','system','system'),
('wf-shop-v1-validate','default','default','workflow-shop-consultant-v1','validate-input','INPUT_VALIDATION','Validate input','{}','{}','{}',1000,1,'ACTIVE','system','system'),
('wf-shop-v1-normalize','default','default','workflow-shop-consultant-v1','normalize-input','INPUT_NORMALIZE','Normalize input','{}','{}','{}',1000,1,'ACTIVE','system','system'),
('wf-shop-v1-intent','default','default','workflow-shop-consultant-v1','classify-intent','INTENT_CLASSIFY','Classify intent','{}','{}','{}',3000,2,'ACTIVE','system','system'),
('wf-shop-v1-entity','default','default','workflow-shop-consultant-v1','extract-entities','ENTITY_EXTRACT','Extract entities','{}','{}','{}',2000,2,'ACTIVE','system','system'),
('wf-shop-v1-branch','default','default','workflow-shop-consultant-v1','route-intent','BRANCH','Route intent','{}','{}','{}',1000,1,'ACTIVE','system','system'),
('wf-shop-v1-summary-parallel','default','default','workflow-shop-consultant-v1','summary-parallel','PARALLEL','Summary evidence','{"maxParallelism":3,"branchTimeoutMs":30000}','{}','{}',30000,1,'ACTIVE','system','system'),
('wf-shop-v1-summary-tool','default','default','workflow-shop-consultant-v1','summary-tool','TOOL','Detailed shop analysis','{"toolCode":"get-shop-detailed-analysis","toolVersion":1,"outputVariable":"shopData","inputMapping":{"shopId":"$.shopId"}}','{}','{}',5000,2,'ACTIVE','system','system'),
('wf-shop-v1-summary-knowledge','default','default','workflow-shop-consultant-v1','summary-knowledge','KNOWLEDGE_RETRIEVE','Enterprise knowledge','{"knowledgeBaseId":"kb-shop-enterprise","knowledgeBaseVersion":1,"queryVariable":"text","resultVariable":"retrievalResults","topK":6}','{}','{}',10000,2,'ACTIVE','system','system'),
('wf-shop-v1-summary-memory','default','default','workflow-shop-consultant-v1','summary-memory','MEMORY_RECALL','Memory recall','{"outputVariable":"memoryRecall"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-summary-join','default','default','workflow-shop-consultant-v1','summary-join','JOIN','Join summary evidence','{"mode":"MERGE_OBJECT"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-summary','default','default','workflow-shop-consultant-v1','summary-llm','LLM','Shop summary','{"useAgentDefaultPrompt":true,"inputMapping":{"question":"$.text","shopData":"$.shopData","knowledge":"$.retrievalResults","memory":"$.memoryRecall"},"outputVariable":"agentOutput","responseFormat":"JSON","citationRequired":true,"maxOutputTokensOverride":1200}','{}','{}',120000,2,'ACTIVE','system','system'),
('wf-shop-v1-summary-citation','default','default','workflow-shop-consultant-v1','summary-citation','CITATION_VALIDATION','Validate citations','{"required":true}','{}','{}',2000,1,'ACTIVE','system','system'),
('wf-shop-v1-qa-parallel','default','default','workflow-shop-consultant-v1','qa-parallel','PARALLEL','QA evidence','{"maxParallelism":4,"branchTimeoutMs":30000}','{}','{}',30000,1,'ACTIVE','system','system'),
('wf-shop-v1-qa-tool','default','default','workflow-shop-consultant-v1','qa-tool','TOOL','Ask about shop','{"toolCode":"ask-about-shop","toolVersion":1,"outputVariable":"shopData","inputMapping":{"shopId":"$.shopId","question":"$.text"}}','{}','{}',5000,2,'ACTIVE','system','system'),
('wf-shop-v1-qa-knowledge','default','default','workflow-shop-consultant-v1','qa-knowledge','KNOWLEDGE_RETRIEVE','QA knowledge','{"knowledgeBaseId":"kb-shop-enterprise","knowledgeBaseVersion":1,"queryVariable":"text","resultVariable":"retrievalResults","topK":8}','{}','{}',10000,2,'ACTIVE','system','system'),
('wf-shop-v1-qa-memory','default','default','workflow-shop-consultant-v1','qa-memory','MEMORY_RECALL','QA memory','{"outputVariable":"memoryRecall"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-qa-join','default','default','workflow-shop-consultant-v1','qa-join','JOIN','Join QA evidence','{"mode":"MERGE_OBJECT"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-qa','default','default','workflow-shop-consultant-v1','qa-llm','LLM','Shop QA','{"useAgentDefaultPrompt":true,"inputMapping":{"question":"$.text","shopData":"$.shopData","knowledge":"$.retrievalResults","memory":"$.memoryRecall"},"outputVariable":"agentOutput","responseFormat":"JSON","citationRequired":true,"maxOutputTokensOverride":1200}','{}','{}',120000,2,'ACTIVE','system','system'),
('wf-shop-v1-qa-citation','default','default','workflow-shop-consultant-v1','qa-citation','CITATION_VALIDATION','Validate citations','{"required":true}','{}','{}',2000,1,'ACTIVE','system','system'),
('wf-shop-v1-compare-tool','default','default','workflow-shop-consultant-v1','compare-tool','TOOL','Compare shops','{"toolCode":"compare-shops","toolVersion":1,"outputVariable":"shopData","inputMapping":{"shopIds":"$.shopIds","aspect":"$.aspect"}}','{}','{}',8000,2,'ACTIVE','system','system'),
('wf-shop-v1-compare-memory','default','default','workflow-shop-consultant-v1','compare-memory','MEMORY_RECALL','Compare memory','{"outputVariable":"memoryRecall"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-compare','default','default','workflow-shop-consultant-v1','compare-llm','LLM','Shop compare','{"useAgentDefaultPrompt":true,"inputMapping":{"question":"$.text","shopData":"$.shopData","memory":"$.memoryRecall"},"outputVariable":"agentOutput","responseFormat":"JSON","maxOutputTokensOverride":1200}','{}','{}',120000,2,'ACTIVE','system','system'),
('wf-shop-v1-compare-citation','default','default','workflow-shop-consultant-v1','compare-citation','CITATION_VALIDATION','Validate citations','{"required":false}','{}','{}',2000,1,'ACTIVE','system','system'),
('wf-shop-v1-recommend-tool','default','default','workflow-shop-consultant-v1','recommend-tool','TOOL','Recommend shops','{"toolCode":"recommend-shops","toolVersion":1,"outputVariable":"recommendations","inputMapping":{"preference":"$.text","category":"$.category","limit":"$.limit"}}','{}','{}',8000,2,'ACTIVE','system','system'),
('wf-shop-v1-recommend-memory','default','default','workflow-shop-consultant-v1','recommend-memory','MEMORY_RECALL','Recommendation memory','{"outputVariable":"memoryRecall"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-recommend','default','default','workflow-shop-consultant-v1','recommend-llm','LLM','Shop recommend','{"useAgentDefaultPrompt":true,"inputMapping":{"question":"$.text","recommendations":"$.recommendations","memory":"$.memoryRecall"},"outputVariable":"agentOutput","responseFormat":"JSON","maxOutputTokensOverride":1200}','{}','{}',120000,2,'ACTIVE','system','system'),
('wf-shop-v1-recommend-citation','default','default','workflow-shop-consultant-v1','recommend-citation','CITATION_VALIDATION','Validate citations','{"required":false}','{}','{}',2000,1,'ACTIVE','system','system'),
('wf-shop-v1-unknown-memory','default','default','workflow-shop-consultant-v1','unknown-memory','MEMORY_RECALL','General memory','{"outputVariable":"memoryRecall"}','{}','{}',3000,1,'ACTIVE','system','system'),
('wf-shop-v1-unknown','default','default','workflow-shop-consultant-v1','unknown-llm','LLM','Safe general answer','{"useAgentDefaultPrompt":true,"inputMapping":{"question":"$.text","memory":"$.memoryRecall"},"outputVariable":"agentOutput","responseFormat":"JSON","maxOutputTokensOverride":800}','{}','{}',120000,2,'ACTIVE','system','system'),
('wf-shop-v1-unknown-citation','default','default','workflow-shop-consultant-v1','unknown-citation','CITATION_VALIDATION','Validate citations','{"required":false}','{}','{}',2000,1,'ACTIVE','system','system'),
('wf-shop-v1-output','default','default','workflow-shop-consultant-v1','validate-output','OUTPUT_VALIDATION','Validate output','{}','{}','{}',2000,1,'ACTIVE','system','system'),
('wf-shop-v1-end','default','default','workflow-shop-consultant-v1','end','END','End','{}','{}','{}',1000,1,'ACTIVE','system','system');

INSERT INTO ai_workflow_edge
(id,tenant_id,workspace_id,workflow_version_id,source_node_code,target_node_code,condition_json,priority,label,status,created_by,updated_by)
VALUES
('wf-native-e01','default','default','workflow-shop-consultant-v1','start','validate-input',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e02','default','default','workflow-shop-consultant-v1','validate-input','normalize-input',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e03','default','default','workflow-shop-consultant-v1','normalize-input','classify-intent',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e04','default','default','workflow-shop-consultant-v1','classify-intent','extract-entities',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e05','default','default','workflow-shop-consultant-v1','extract-entities','route-intent',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e06','default','default','workflow-shop-consultant-v1','route-intent','summary-parallel','{"eq":[{"var":"intent"},"SHOP_SUMMARY"]}',100,'summary','ACTIVE','system','system'),
('wf-native-e07','default','default','workflow-shop-consultant-v1','route-intent','qa-parallel','{"in":[{"var":"intent"},["SHOP_QA","KNOWLEDGE_QUERY"]]}',90,'qa','ACTIVE','system','system'),
('wf-native-e08','default','default','workflow-shop-consultant-v1','route-intent','compare-tool','{"eq":[{"var":"intent"},"SHOP_COMPARE"]}',80,'compare','ACTIVE','system','system'),
('wf-native-e09','default','default','workflow-shop-consultant-v1','route-intent','recommend-tool','{"eq":[{"var":"intent"},"SHOP_RECOMMEND"]}',70,'recommend','ACTIVE','system','system'),
('wf-native-e10','default','default','workflow-shop-consultant-v1','route-intent','unknown-memory','{"not":{"in":[{"var":"intent"},["SHOP_SUMMARY","SHOP_QA","KNOWLEDGE_QUERY","SHOP_COMPARE","SHOP_RECOMMEND"]]}}',0,'default','ACTIVE','system','system'),
('wf-native-e11','default','default','workflow-shop-consultant-v1','summary-parallel','summary-tool',NULL,30,'tool','ACTIVE','system','system'),
('wf-native-e12','default','default','workflow-shop-consultant-v1','summary-parallel','summary-knowledge',NULL,20,'knowledge','ACTIVE','system','system'),
('wf-native-e13','default','default','workflow-shop-consultant-v1','summary-parallel','summary-memory',NULL,10,'memory','ACTIVE','system','system'),
('wf-native-e14','default','default','workflow-shop-consultant-v1','summary-tool','summary-join',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e15','default','default','workflow-shop-consultant-v1','summary-knowledge','summary-join',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e16','default','default','workflow-shop-consultant-v1','summary-memory','summary-join',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e17','default','default','workflow-shop-consultant-v1','summary-join','summary-llm',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e18','default','default','workflow-shop-consultant-v1','summary-llm','summary-citation',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e19','default','default','workflow-shop-consultant-v1','summary-citation','validate-output',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e20','default','default','workflow-shop-consultant-v1','qa-parallel','qa-tool',NULL,30,'tool','ACTIVE','system','system'),
('wf-native-e21','default','default','workflow-shop-consultant-v1','qa-parallel','qa-knowledge',NULL,20,'knowledge','ACTIVE','system','system'),
('wf-native-e22','default','default','workflow-shop-consultant-v1','qa-parallel','qa-memory',NULL,10,'memory','ACTIVE','system','system'),
('wf-native-e23','default','default','workflow-shop-consultant-v1','qa-tool','qa-join',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e24','default','default','workflow-shop-consultant-v1','qa-knowledge','qa-join',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e25','default','default','workflow-shop-consultant-v1','qa-memory','qa-join',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e26','default','default','workflow-shop-consultant-v1','qa-join','qa-llm',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e27','default','default','workflow-shop-consultant-v1','qa-llm','qa-citation',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e28','default','default','workflow-shop-consultant-v1','qa-citation','validate-output',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e29','default','default','workflow-shop-consultant-v1','compare-tool','compare-memory',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e30','default','default','workflow-shop-consultant-v1','compare-memory','compare-llm',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e31','default','default','workflow-shop-consultant-v1','compare-llm','compare-citation',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e32','default','default','workflow-shop-consultant-v1','compare-citation','validate-output',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e33','default','default','workflow-shop-consultant-v1','recommend-tool','recommend-memory',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e34','default','default','workflow-shop-consultant-v1','recommend-memory','recommend-llm',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e35','default','default','workflow-shop-consultant-v1','recommend-llm','recommend-citation',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e36','default','default','workflow-shop-consultant-v1','recommend-citation','validate-output',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e37','default','default','workflow-shop-consultant-v1','unknown-memory','unknown-llm',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e38','default','default','workflow-shop-consultant-v1','unknown-llm','unknown-citation',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e39','default','default','workflow-shop-consultant-v1','unknown-citation','validate-output',NULL,0,NULL,'ACTIVE','system','system'),
('wf-native-e40','default','default','workflow-shop-consultant-v1','validate-output','end',NULL,0,NULL,'ACTIVE','system','system');
