CREATE TABLE IF NOT EXISTS ai_mcp_server (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    workspace_id VARCHAR(64) NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    namespace VARCHAR(128) NOT NULL,
    transport VARCHAR(32) NOT NULL,
    endpoint_or_command VARCHAR(1000) NOT NULL,
    secret_ref VARCHAR(255) NULL,
    allowed_tools_json LONGTEXT NOT NULL,
    timeout_ms INT NOT NULL,
    allow_private_network TINYINT(1) NOT NULL DEFAULT 0,
    health_status VARCHAR(32) NOT NULL,
    enabled TINYINT(1) NOT NULL,
    last_sync_at TIMESTAMP(3) NULL,
    status VARCHAR(32) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_mcp_server_code (tenant_id, workspace_id, code),
    KEY idx_ai_mcp_server_health (tenant_id, workspace_id, enabled, health_status, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_mcp_tool_binding (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    workspace_id VARCHAR(64) NOT NULL,
    mcp_server_id VARCHAR(64) NOT NULL,
    remote_tool_name VARCHAR(255) NOT NULL,
    tool_id VARCHAR(64) NOT NULL,
    tool_version_id VARCHAR(64) NOT NULL,
    remote_schema_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_by VARCHAR(64) NOT NULL,
    updated_by VARCHAR(64) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    UNIQUE KEY uk_ai_mcp_tool_remote (mcp_server_id, remote_tool_name),
    KEY idx_ai_mcp_tool_registry (tenant_id, workspace_id, tool_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
